application: learn-to-code
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: web/index.html
  upload: web/index.html
  
- url: /static
  static_dir: web/

- url: /.*
  script: wsgi.application
